spring:
  boot:
    admin:
       url: http://localhost:2000
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
  security:
    user:
      name: admin
      password: password

server:
  port: 8888
logging:
  file: target/${spring.application.name}.log