spring:
  boot:
    admin:
      url: http://localhost:2000
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  security:
    user:
      password: password
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
server:
  port: 8888
logging:
  file: target/${spring.application.name}.log
security:
  user:
    name: admin
    password: admin123
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: ALWAYS