spring:
  security:
    user:
      name: user
      password: password
  boot:
    admin:
      client:
        username: user
        password: password
        enabled: true
        url: http://localhost:2000
        period: 10000
        auto-registration: true
        instance:
          name: ${spring.application.name}
          metadata:
            user.name: user
            user.password: password
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
server:
  port: 8888
logging:
  file: target/${spring.application.name}.log
management:
  endpoints:
    enabled-by-default: false
#    web:
#      exposure:
#        include: '*'
  endpoint:
    refresh:
      enabled: true
    mappings:
      enabled: true
    threaddump:
      enabled: true
    beans:
      enabled: true
    metrics:
      enabled: true
    configprops:
      enabled: true
    env:
      enabled: true
    health:
      show-details: ALWAYS
      enabled: true