version: '3'
services:
  rabbitmq:
    ports:
    - 5672:5672
  config:
    build: uconfig
    ports:
    - 8888:8888
  registry:
    build: udiscovery
    ports:
    - 8761:8761
  gateway:
    build: ugateway
    ports:
    - 8080:80
  college-service:
    build: college-service
    ports:
    - 9000:9000
  college-mongodb:
    build: mongodb
    ports:
    - 25000:27017
  monitoring:
    build: umonitoring
    ports:
    - 7070:7070
  uadmin:
    build: uadmin
    ports:
    - 2000:2000