logging:
  level:
    org:
      hibernate:
        SQL: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
management:
  server:
    address: 127.0.0.1
    port: 8081
#  security:
#    enabled: false
security:
  strengthPasswordEncoder: 10
server:
  port: 8090
  servlet:
    context-path: /auth
spring:
  application:
    name: auth-services
  datasource:
    driver:
      class: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/cloudwalkers
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect