FROM java:8-jre
MAINTAINER NIJO GEORGE P <nijomon@gmail.com>

ADD ./target/umonitoring-0.0.1-SNAPSHOT.jar /app/
CMD ["java", "-Xmx200m", "-jar", "/app/umonitoring-0.0.1-SNAPSHOT.jar"]

EXPOSE 8989 8080