spring:
  security:
    user:
      name: user
      password: password
  boot:
    admin:
      ui:
        title: University ERP Administration
      client:
        username: user
        password: password
        instance:
          metadata:
            user.name: user
            user.password: password
      url: http://localhost:2000
  application:
    name: boot-admin-server
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false
      password: password
      username: user
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
server:
  port: 2000
logging:
  file: target/${spring.application.name}.log