spring: 
  boot:
    admin:
       url: http://localhost:2000
  application:
    name: bootadmin
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
management:
  security:
    enabled: false
security:
  user: 
    name: admin
    password: admin123
server:
  port: 8761
logging:
  file: target/${spring.application.name}.log