spring:
  boot.admin.client:
    url: http://localhost:2000
    instance:
      metadata:
        user.name: user
        user.password: password
  application:
    name: college-services
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false
      password: password
      username: user
  data:
    mongodb:
      host: localhost
      database: universityerp
      port: 27017
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
logging:
  file: target/${spring.application.name}.log
#security:
#  user:
#    name: user
#    password: password