spring:
  security:
    user:
      name: user
      password: password
  boot:
    admin:
      client:
        username: user
        password: password
        enabled: true
        url: http://localhost:2000
        period: 10000
        auto-registration: true
        instance:
          name: ${spring.application.name}
          metadata:
            user.name: user
            user.password: password
  application:
    name: college-services
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false
      password: password
      username: user
  data:
    mongodb:
      host: localhost
      database: universityerp
      port: 27017
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
logging:
  file: target/${spring.application.name}.log
  pattern.file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta}
    %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint}
    %m%n%wEx'
management:
  endpoints:
    web:
      exposure:
        include: '*'