logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    region: default
    registryFetchIntervalSeconds : 5
#    serviceUrl:
#      defaultZone: http://admin:password@localhost:7000/eureka/

#spring:
#  rabbitmq:
#    host: rabbitmq